name: sync

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'

jobs:
  xiaoyahelper:
    runs-on: ubuntu-latest
    name: xiaoyahelper
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: xiaoyahelper
          run: |
            mv ./aliyun_clear.sh ./aliyun_clear.sh.backup
            wget -O ./aliyun_clear.sh https://xiaoyahelper.zengge99.eu.org/aliyun_clear.sh
            if [ -f ./aliyun_clear.sh ]; then
                rm -rf ./aliyun_clear.sh.backup
            else
                mv ./aliyun_clear.sh.backup ./aliyun_clear.sh
            fi

        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: 'chore: backup xiaoyahelper'
            branch: master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
